// A curated list of Material Design icons for the icon picker
// You can add/remove icons as needed for your use case
export const MATERIAL_ICONS = [
  { name: "MdHome", label: "Home" },
  { name: "MdSchool", label: "School" },
  { name: "MdBook", label: "Book" },
  { name: "MdPerson", label: "Person" },
  { name: "MdStar", label: "Star" },
  { name: "MdCheck", label: "Check" },
  { name: "MdClose", label: "Close" },
  { name: "MdEdit", label: "Edit" },
  { name: "MdDelete", label: "Delete" },
  { name: "MdInfo", label: "Info" },
  { name: "MdSettings", label: "Settings" },
  { name: "MdSearch", label: "Search" },
  { name: "MdFavorite", label: "Favorite" },
  { name: "MdLock", label: "Lock" },
  { name: "MdVisibility", label: "Visibility" },
  { name: "MdVisibilityOff", label: "Visibility Off" },
  { name: "MdMenu", label: "Menu" },
  { name: "MdArrowForward", label: "Arrow Forward" },
  { name: "MdArrowBack", label: "Arrow Back" },
  { name: "MdExpandMore", label: "Expand More" },
  { name: "MdExpandLess", label: "Expand Less" },
  { name: "MdAdd", label: "Add" },
  { name: "MdRemove", label: "Remove" },
  { name: "MdNotifications", label: "Notifications" },
  { name: "MdEmail", label: "Email" },
  { name: "MdCloudUpload", label: "Cloud Upload" },
  { name: "MdAttachFile", label: "Attach File" },
  { name: "MdFolder", label: "Folder" },
  { name: "MdDescription", label: "Description" },
  { name: "MdImage", label: "Image" },
  { name: "MdVideoLibrary", label: "Video Library" },
  { name: "MdHeadset", label: "Headset" },
  { name: "MdShoppingCart", label: "Shopping Cart" },
  { name: "MdCreditCard", label: "Credit Card" },
  { name: "MdEvent", label: "Event" },
  { name: "MdAlarm", label: "Alarm" },
  { name: "MdTimer", label: "Timer" },
  { name: "MdLocationOn", label: "Location On" },
  { name: "MdPublic", label: "Public" },
  { name: "MdPalette", label: "Palette" },
  { name: "MdBrush", label: "Brush" },
  { name: "MdCameraAlt", label: "Camera Alt" },
  { name: "MdPhotoCamera", label: "Photo Camera" },
  { name: "MdMic", label: "Mic" },
  { name: "MdVolumeUp", label: "Volume Up" },
  { name: "MdPlayArrow", label: "Play Arrow" },
  { name: "MdPause", label: "Pause" },
  { name: "MdStop", label: "Stop" },
  { name: "MdSkipNext", label: "Skip Next" },
  { name: "MdSkipPrevious", label: "Skip Previous" },
  { name: "MdFastForward", label: "Fast Forward" },
  { name: "MdFastRewind", label: "Fast Rewind" },
  { name: "MdRepeat", label: "Repeat" },
  { name: "MdShuffle", label: "Shuffle" },
  { name: "MdVolumeOff", label: "Volume Off" },
  { name: "MdVolumeMute", label: "Volume Mute" },
  { name: "MdPlaylistAdd", label: "Playlist Add" },
  { name: "MdQueueMusic", label: "Queue Music" },
  { name: "MdLibraryMusic", label: "Library Music" },
  { name: "MdAlbum", label: "Album" },
  { name: "MdArtist", label: "Artist" },
  { name: "MdArtTrack", label: "Art Track" },
  { name: "MdAudiotrack", label: "Audiotrack" },
  { name: "MdSubtitles", label: "Subtitles" },
  { name: "MdClosedCaption", label: "Closed Caption" },
  { name: "MdEqualizer", label: "Equalizer" },
  { name: "MdGraphicEq", label: "Graphic Eq" },
  { name: "MdHighQuality", label: "High Quality" },
  { name: "MdVideoLabel", label: "Video Label" },
  { name: "MdWeb", label: "Web" },
  { name: "MdGames", label: "Games" },
  { name: "MdToys", label: "Toys" },
  { name: "MdSportsEsports", label: "Sports Esports" },
  { name: "MdFitnessCenter", label: "Fitness Center" },
  { name: "MdSpa", label: "Spa" },
  { name: "MdSelfImprovement", label: "Self Improvement" },
  { name: "MdWork", label: "Work" },
  { name: "MdBusiness", label: "Business" },
  { name: "MdAccountBalance", label: "Account Balance" },
  { name: "MdCurrencyExchange", label: "Currency Exchange" },
  { name: "MdAnalytics", label: "Analytics" },
  { name: "MdPieChart", label: "Pie Chart" },
  { name: "MdShowChart", label: "Show Chart" },
  { name: "MdTimeline", label: "Timeline" },
  { name: "MdTrendingUp", label: "Trending Up" },
  { name: "MdTrendingDown", label: "Trending Down" },
  { name: "MdTrendingFlat", label: "Trending Flat" },
  { name: "MdAttachMoney", label: "Attach Money" },
  { name: "MdEuro", label: "Euro" },
  { name: "MdDollar", label: "Dollar" },
  { name: "MdPayments", label: "Payments" },
  { name: "MdAccountBalanceWallet", label: "Account Balance Wallet" },
  { name: "MdSavings", label: "Savings" },
  { name: "MdReceipt", label: "Receipt" },
  { name: "MdShoppingCartCheckout", label: "Shopping Cart Checkout" },
  { name: "MdPointOfSale", label: "Point Of Sale" },
  { name: "MdToll", label: "Toll" },
  { name: "MdDiscount", label: "Discount" },
  { name: "MdLoyalty", label: "Loyalty" },
  { name: "MdRedeem", label: "Redeem" },
  { name: "MdStars", label: "Stars" },
  { name: "MdWorkspacePremium", label: "Workspace Premium" },
  { name: "MdMilitaryTech", label: "Military Tech" },
  { name: "MdVerified", label: "Verified" },
  { name: "MdGavel", label: "Gavel" },
  { name: "MdPolicy", label: "Policy" },
  { name: "MdFingerprint", label: "Fingerprint" },
  { name: "MdFactCheck", label: "Fact Check" },
  { name: "MdPrivacyTip", label: "Privacy Tip" },
  { name: "MdAssignment", label: "Assignment" },
];
